test:
  stage: test
  image: node:14.17.6
  script:
    - yarn build
  except:
    - main

setup:
  stage: build
  image: ruby:3.0.3

  script:
    - cd ruby
    - bundle install
    - bundle exe collect_versions.rb
    - bundle exe release_posts.rb
    - bundle exe collect_notes.rb
  artifacts:
    paths:
      - ruby/all.js
      - ruby/releases.js
      - ruby/notes.js
    expire_in: 1 day
  only:
    - main

pages:
  stage: deploy
  image: node:14.17.6

  script:
    - ./setup.sh
    - yarn install
    - yarn build
    - mv public old
    - mv build public
  artifacts:
    paths:
      - public
    expire_in: 1 day

  only:
    - main
