test:
  stage: test
  image: node:20.11.1
  script:
    - yarn install
    - yarn build
  except:
    - main

setup:
  stage: build
  image: ruby:$RUBY_VERSION
  script:
    - bundle config set --local path vendor
    - make data
  artifacts:
    paths:
      - ruby/all.js
      - ruby/releases.js
      - ruby/notes.js
      - ruby/versions.js
      - ruby/path.json
      - ruby/alerts.js
    expire_in: 1 day
  cache:
    key: "ruby-$RUBY_CACHE_KEY"
    paths:
      - ruby/vendor
  variables:
    RUBY_VERSION: "3.0.5"
    RUBY_CACHE_KEY: "3.0"
  only:
    - main

pages:
  stage: deploy
  image: node:20.11.1

  script:
    - ./setup.sh
    - yarn install
    - yarn build
    - mv public old
    - mv build public
  artifacts:
    paths:
      - public
    expire_in: 1 day

  only:
    - main
